# Generated by Django 6.0.2 on 2026-03-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard', '0010_activeshift'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jobcard',
            name='unique_jobcard_per_shift_line_date',
        ),
        migrations.AddConstraint(
            model_name='jobcard',
            constraint=models.UniqueConstraint(fields=('date', 'line', 'shift', 'wo_number'), name='unique_jobcard_per_workorder'),
        ),
    ]
